stages:
  - Build
  - Run

build: 
 stage: Build
 before_script:
   - docker buildx inspect --bootstrap
 script:
   - docker buildx build --platform=ppc64le -t local-build . --load

   - docker image ls
 tags: 
     - docker-buildx

Run:
  stage: Run
  script:
    - docker run --platform ppc64le --rm local-build
  tags: 
    - docker-buildx
